# Service Account Configuration (GCP Workload Identity)
serviceAccount:
  enabled: true
  name: retail-kanopy-sa  # Debe coincidir con KSA_NAME que creaste en Kubernetes

# Mount GCP credential config AND projected service account token
extraVolumes:
  - name: gcp-creds
    configMap:
      # ConfigMap creado con:
      # kubectl create configmap gcp-wif-config-retail \
      #   --from-file=credential-configuration.json=gcp-credential-config.json
      name: gcp-wif-config-retail
  - name: gcp-token
    projected:
      sources:
        - serviceAccountToken:
            path: token
            expirationSeconds: 3600  # token rotativo
            audience: "//iam.googleapis.com/projects/531154772515/locations/global/workloadIdentityPools/kanopy-retail-wif-pool/providers/kanopy-retail-provider"

extraVolumeMounts:
  - name: gcp-creds
    mountPath: /etc/gcp
    readOnly: true
  - name: gcp-token
    mountPath: /var/run/service-account
    readOnly: true

# Secret references for sensitive data (tus env de .env.local)
envSecrets:
  # Mongo / app core
  MONGODB_URI: retail-store-v2-staging
  DATABASE_NAME: retail-store-v2-staging
  COLLECTION_NAME: retail-store-v2-staging

  # Frontend
  NEXT_PUBLIC_CHATBOT_PASSWORD: retail-store-v2-staging
  NEXT_PUBLIC_GCP_INVOICE_URL: retail-store-v2-staging

  # Dataworkz (RAG)
  DATAWORKZ_SERVICE: retail-store-v2-staging
  DATAWORKZ_TOKEN: retail-store-v2-staging
  DATAWORKZ_AGENT_ID: retail-store-v2-staging
  DATAWORKZ_LLM_ID: retail-store-v2-staging

# Environment variables for GCP (NO sensibles)
env:
  NODE_ENV: "staging"
  GOOGLE_APPLICATION_CREDENTIALS: /etc/gcp/credential-configuration.json
  GCP_PROJECT_ID: ist-retail-demo
  GCP_LOCATION: us-central1
  # Si luego usás Vertex directamente:
  # VERTEXAI_COMPLETIONS_MODEL: gemini-2.0-flash-001
